### ISSUE TITLE
Consider a license more permissive than AGPL-3.0

### ISSUE THREAD

**Issue by SEJeff** [blockworks-foundation/lite-rpc#239]
To mesh with most of the other ecosystem projects, would it be possible to consider a more permissive license? If not, anyone considering implementing a stack ontop of lite-rpc for commercial services might have to implement their own TPU client.

Examples:
* [tinydancer](https://github.com/tinydancer-io/tinydancer) - MIT
* [solana](https://github.com/solana-labs/solana) - Apache 2.0
* [firedancer](https://github.com/firedancer-io/firedancer) - Apache 2.0
* [yellowstone-grpc](https://github.com/rpcpool/yellowstone-grpc) - Apache 2.0

**Comment by mschneider** [comment]
AGPL is a common license for network services a lot of successful businesses are enabled to build a stack "on top" of AGPL projects like mongo db. Solana's ecosystem has a grave image problem, because of the closed source policies that most projects except for Mango follow, we would like help improve it and push more projects to open source.

In case you want to use the code in a proprietary application and want a commercial license, please reach out on discord, introduce your project and explain how you are planning to improve lite-rpc. We're open to find solutions on a case by case basis, likely free of charge.
