### ISSUE TITLE
Fix: Postgres worker keeps on creating random connections. Limit connections

### ISSUE THREAD

**Issue by aniketfuryrocks** [blockworks-foundation/lite-rpc#60]

**Comment by mschneider** [comment]
talked with @riordanp about this on the weekend, he mentioned this is very hard to prevent due to how the fly redeployment works. basically we lack control over the issue. but I contacted the sql admins, they will setup a server side proxy to close unused connections after one minute. this way the db connections will quickly free up when not used anymore
